### ISSUE TITLE
Configuration paradox

### ISSUE THREAD

**Issue by sspreitzer** [linux-system-roles/postfix#15]
This role introduces a paradox.

* The daemon can not be started if the configuration is not valid for the system
* The role can not change the daemon configuration unless the daemon is started

There are unknown cases in which by external dependencies the configuration is inapplicable.

* Eg. system has ipv6 disabled but localhost in /etc/hosts is 127.0.0.1 and ::1. postfix will not start as it can not bind to ::1

Please solve the configuration paradox.

**Comment by sspreitzer** [comment]
Can be solved by invoking postconf prior service enablement.

**Comment by richm** [comment]
patches welcome

**Comment by sspreitzer** [comment]
Okay, I will put it on my todo list

**Comment by sspreitzer** [comment]
@richm you can assign the issue to me

**Comment by scrubby** [comment]
Any updates about this paradox? I'm running into myself as well.

**Comment by richm** [comment]
> Any updates about this paradox? I'm running into myself as well.

No updates - PRs/patches welcome

**Comment by scrubby** [comment]
Wouldn't the fix be as simple as splitting the enable service and the start service? 
So in the main.yml change this
```
- name: Enable Postfix
  service:
    name: postfix
    state: started
    enabled: true
```

To this
```
- name: Enable Postfix
  service:
    name: postfix
    enabled: true
```

And then in the end of the file, in case it's run without applying a custom conf>
```
- name: Enable Postfix
  service:
    name: postfix
    state: started
```
